[workspace]
resolver = "2"
members = [
    "kernel",
    "user/userlib",
    "subsystems/*",
    "user/apps/*",
    "user/musl/hello",
    # "user/musl/async_test",  # Temporarily disabled: tokio depends on mio/socket2 which fail in no_std
    "user/musl/ftest",
]
